# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: PCS Validation

on:
  push:
    paths-ignore:
      - '*.md'
      - '*.py'
      - '*.txt'
    branches: [ "main" ]
  pull_request:
    paths-ignore:
      - '*.md'
    branches: [ "main" ]

jobs:

  build_and_test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@main

    - name: Setup Go
      uses: actions/setup-go@main
      with:
          go-version: '1.24.x'
          cache: true
          cache-dependency-path: "**/go.sum"
          
    - name: Setup JDK
      uses: actions/setup-java@main
      with:
        distribution: 'oracle'
        java-version: '21'

    - name: Compile on Linux or MacOS
      if: runner.os == 'Linux' || runner.os == 'macOS'
      run: |
        bash ./compile.sh

    - name: Run on Linux or MacOS
      if: runner.os == 'Linux' || runner.os == 'macOS'
      run: |
        bash ./run.sh

    - name: Compile on Windows
      if: runner.os == 'Windows'
      run: |
        .\compile.bat

    - name: Run on Windows
      if: runner.os == 'Windows'
      run: |
        .\run.bat
