# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: PCS Validation

on:
  push:
    paths-ignore:
      - '*.md'
      - '*.py'
      - '*.txt'
      - '**.yml'
    branches: [ "main" ]
  pull_request:
    paths-ignore:
      - '*.md'
      - '**.yml'
    branches: [ "main" ]

jobs:

  build_and_test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@main

    - name: Setup Go
      uses: actions/setup-go@main
      with:
          go-version: '1.24.x'
          cache: true
          cache-dependency-path: "**/go.sum"
          
    - name: Setup JDK
      uses: actions/setup-java@main
      with:
        distribution: 'oracle'
        java-version: '21'

    - name: Compile
      run: |
        cd producer
        go get
        go install -v ./...
        cd ../consumer
        javac *.java
        cd ../swinger
        javac *.java

    - name: Run
      run: |
        producer  100  saucisse.data
        java  -cp consumer  consumer  100  saucisse.data
